name: Psalm Static analysis

on:
  push:
    paths-ignore: '.*'
  pull_request:

jobs:
  psalm:
    name: Psalm
    permissions:
      actions: read
      checks: read
      contents: read
      deployments: none
      id-token: none
      issues: write
      discussions: read
      packages: read
      pages: none
      pull-requests: write
      repository-projects: read
      security-events: write
      statuses: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Psalm code analysis
        uses: docker://ghcr.io/psalm/psalm-github-actions
        with:
          security_analysis: true
          report_file: results.sarif
          findUnusedCode: true
      - name: Upload Security Analysis results to GitHub
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: results.sarif
